import pandas as pd

def Creating_The_Board():
    # List of cities
    cities = ['Helena', 'Winnipeg','Calgary','Vancouver','Seattle','Portland','San Francesco',
              'Los Angeles','Salt Lake City','Sault St. Marie','Montreal','Toronto','Boston',
              'New York','Duluth','Pittsburgh','Chicago','Washington DC', 'Omaha','Denver',
              'Las Vegas','Phoenix','Sante Fe','El Palo','Oklahoma City','Kansas City', 'Saint Louis',
              'Nashville','Raleigh','Little Rock','Alanta','Charleston','Miami','Dallas',
              'Houston','New Orleans','Miami']


    fill_in_color= {
        city: {other_city: [('no_Connection', 0)] for other_city in cities} for city in cities
    }

    # create the board
    board= pd.DataFrame(fill_in_color)

    # Pain painstakingly hand entered all the board connections.
    board.loc['Helena', 'Winnipeg'] = [('blue', 4)]
    board.loc['Winnipeg', 'Helena'] = [('blue', 4)]
    board.loc['Helena', 'Calgary'] = [('any',4)]
    board.loc['Calgary','Helena'] = [('any',4)]
    board.loc['Seattle','Helena'] = [('yellow',6)]
    board.loc['Helena', 'Seattle'] = [('yellow',6)]
    board.loc['Helena','Duluth'] = [('orange', 6)]
    board.loc['Duluth','Helena'] = [('orange', 6)]
    board.loc['Helena','Omaha'] = [('red',5)]
    board.loc['Omaha','Helena'] = [('red',5)]
    board.loc['Helena', 'Salt Lake City']= [('pink',3)]
    board.loc['Salt Lake City', 'Helena'] = [('pink',3)]
    board.loc['Vancouver', 'Calgary'] = [('any', 3)]
    board.loc['Calgary', 'Vancouver'] = [('any',3)]
    board.loc['Vancouver', 'Seattle'] = [('any',1)]
    board.loc['Seattle', 'Portland']= [('any',1)]
    board.loc['Portland', 'Seattle'] = [('any',1)]
    board.loc['Seattle', 'Calgary'] = [('any',4)]
    board.loc['Calgary','Seattle'] = [('any', 4)]
    board.loc['Calgary', 'Winnipeg']= [('white',6)]
    board.loc['Winnipeg', 'Calgary'] = [('white',6)]
    board.loc['Winnipeg','Duluth'] = [('black',5)]
    board.loc['Duluth' , 'Winnipeg'] = [('black',5)]
    board.loc['Winnipeg','Sault St. Marie'] =[ ('any',6)]
    board.loc['Sault St. Marie','Winnipeg'] = [('any',6)]
    board.loc['Sault St. Marie', 'Montreal'] = [('black',5)]
    board.loc['Montreal','Sault St. Marie'] = [('black', 5)]
    board.loc['Sault St. Marie', 'Toronto'] = [('any', 2)]
    board.loc['Toronto', 'Sault St. Marie'] = [('any',2)]
    board.loc['Sault St. Marie', 'Duluth'] = [('any', 3)]
    board.loc['Duluth', 'Sault St. Marie'] = [('any', 3)]
    board.loc['Duluth', 'Omaha'] = [('any',2)]
    board.loc['Omaha', 'Duluth'] = [('any', 2)]
    board.loc['Duluth','Chicago']= [('red',3)]
    board.loc['Chicago','Duluth'] = [('red',3)]
    board.loc['Duluth','Toronto'] = [('pink',6)]
    board.loc['Toronto','Duluth'] = [('pink', 6)]
    board.loc['Toronto','Montreal']= [('any',3)]
    board.loc['Montreal','Toronto']= [('any',3)]
    board.loc['Toronto', 'Chicago'] = [('white',4)]
    board.loc['Chicago','Toronto'] = [('white',4)]
    board.loc['Toronto', 'Pittsburgh'] = [('any',2)]
    board.loc['Pittsburgh', 'Toronto'] = [('any',2)]
    board.loc['Montreal', 'Boston'] = [('any',2),('any',2)]
    board.loc['Boston', 'Montreal'] = [('any',2),('any',2)]
    board.loc['Montreal', 'New York'] = [('blue',3)]
    board.loc['New York', 'Montreal']= [('blue',3)]
    board.loc['Boston','New York'] = [('yellow',2),('red',2)]
    board.loc['New York', 'Boston'] = [('yellow',2),('red',2)]
    board.loc['New York', 'Pittsburgh'] = [('white',2),('green',2)]
    board.loc['Pittsburgh', 'New York'] = [('white',2),('green',2)]
    board.loc['New York', 'Washington DC']= [('orange',2),('black',2)]
    board.loc['Washington DC', 'New York']=  [('orange',2),('black',2)]
    board.loc['Pittsburgh','Washington DC'] = [('any',2)]
    board.loc['Washington DC', 'Pittsburgh']= [('any',2)]
    board.loc['Pittsburgh','Raleigh'] = [('any',2)]
    board.loc['Raleigh','Pittsburgh'] = [('any', 2)]
    board.loc['Pittsburgh', 'Nashville'] = [('yellow',4)]
    board.loc['Nashville','Pittsburgh'] = [('yellow', 4)]
    board.loc['Pittsburgh', 'Saint Louis'] = [('green',5)]
    board.loc['Saint Louis', 'Pittsburgh'] = [('green',5)]
    board.loc['Pittsburgh','Chicago'] = [('orange',3),('black',3)]
    board.loc['Chicago','Pittsburgh'] = [('orange', 3), ('black', 3)]
    board.loc['Chicago','Saint Louis'] = [('white',2),('green',2)]
    board.loc['Saint Louis','Chicago']= [('white',2),('green',2)]
    board.loc['Chicago','Omaha'] = [('blue',4)]
    board.loc['Omaha','Chicago'] = [('blue',4)]
    board.loc['Omaha','Kansas City'] = [('any',1),('any',1)]
    board.loc['Kansas City','Omaha'] = [('any',1),('any',1)]
    board.loc['Omaha','Denver'] = [('pink',4)]
    board.loc['Denver','Omaha'] = [('pink',4)]
    board.loc['Denver','Kansas City'] = [('orange',4),('black',4)]
    board.loc['Kansas City','Denver'] = [('orange',4),('black',4)]
    board.loc['Denver','Oklahoma City']= [('red',4)]
    board.loc['Oklahoma City','Denver'] = [('red',4)]
    board.loc['Denver','Sante Fe'] = [('any',2)]
    board.loc['Sante Fe','Denver'] = [('any',2)]
    board.loc['Denver','Phoenix'] = [('white',2)]
    board.loc['Phoenix','Denver'] = [('white',2)]
    board.loc['Denver', 'Salt Lake City'] = [('red',3),('yellow',3)]
    board.loc['Salt Lake City', 'Denver'] = [('red',3),('yellow',3)]
    board.loc['Salt Lake City', 'Portland'] = [('blue',6)]
    board.loc['Portland', 'Salt Lake City'] = [('blue',6)]
    board.loc['Salt Lake City', 'Las Vegas'] = [('orange',3)]
    board.loc['Las Vegas','Salt Lake City'] = [('orange',3)]
    board.loc['Salt Lake City','San Francesco'] = [('orange',5),('white',5)]
    board.loc['San Francesco','Salt Lake City'] = [('orange', 5), ('white', 5)]
    board.loc['Portland','San Francesco'] = [('pink',5),('green',5)]
    board.loc['San Francesco','Portland'] = [('pink',5),('green',5)]
    board.loc['Washington DC','Raleigh']= [('any',2),('any',2)]
    board.loc['Raleigh','Washington DC'] = [('any',2), ('any',2)]
    board.loc['San Francesco','Los Angeles'] = [('pink',3),('yellow',3)]
    board.loc['Los Angeles','San Francesco'] = [('pink',3),('yellow',3)]
    board.loc['Los Angeles','Las Vegas']=[('any',2)]
    board.loc['Las Vegas', 'Los Angeles'] = [('any',2)]
    board.loc['Los Angeles', 'Phoenix'] = [('any',2)]
    board.loc['Phoenix','Los Angeles'] = [('any',2)]
    board.loc['Los Angeles','El Palo'] = [('black',6)]
    board.loc['El Palo','Los Angeles'] = [('black',6)]
    board.loc['Phoenix','El Palo'] = [('any',3)]
    board.loc['El Palo','Phoenix'] = [('any',3)]
    board.loc['Phoenix','Sante Fe'] = [('any', 3)]
    board.loc['Sante Fe', 'Phoenix'] = [('any',3)]
    board.loc['Sante Fe', 'Oklahoma City'] = [('blue',3)]
    board.loc['Oklahoma City','Sante Fe'] = [('blue',3)]
    board.loc['Sante Fe', 'El Palo'] = [('any',2)]
    board.loc['El Palo','Sante Fe'] = [('any', 2)]
    board.loc['Oklahoma City','El Palo']= [('yellow',6)]
    board.loc['El Palo', 'Oklahoma City'] = [('yellow',6)]
    board.loc['Oklahoma City','Dallas'] = [('any',2),('any',2)]
    board.loc['Dallas','Oklahoma City']= [('any',2),('any',2)]
    board.loc['Oklahoma City','Little Rock'] = [('any',2)]
    board.loc['Little Rock','Oklahoma City']= [('any',2)]
    board.loc['Oklahoma City','Kansas City'] = [('any',2),('any',2)]
    board.loc['Kansas City', 'Oklahoma City'] = [('any',2),('any',2)]
    board.loc['Kansas City','Saint Louis'] = [('blue',2),('pink',2)]
    board.loc['Omaha','Kansas City']= [('any',1)]
    board.loc['Kansas City','Omaha'] = [('any',1)]
    board.loc['Saint Louis','Kansas City'] = [('blue',2),('pink',2)]
    board.loc['Saint Louis','Little Rock'] = [('any',2)]
    board.loc['Little Rock','Saint Louis'] = [('any',2)]
    board.loc['Saint Louis','Nashville'] = [('any',2)]
    board.loc['Nashville','Saint Louis'] = [('any',2)]
    board.loc['Nashville','Little Rock'] = [('white',3)]
    board.loc['Little Rock','Nashville'] = [('white',3)]
    board.loc['Nashville','Alanta']= [('any',1)]
    board.loc['Alanta','Nashville'] = [('any',1)]
    board.loc['Nashville','Raleigh'] = [('black',3)]
    board.loc['Raleigh','Nashville']= [('black',3)]
    board.loc['Raleigh','Charleston'] = [('any',2)]
    board.loc['Charleston','Raleigh'] = [('any',2)]
    board.loc['Raleigh','Alanta'] = [('any',2),('any',2)]
    board.loc['Alanta','Raleigh']= [('any',2),('any',2)]
    board.loc['Charleston','Miami']= [('pink',4)]
    board.loc['Miami','Charleston']= [('pink',4)]
    board.loc['Alanta','Charleston']= [('any', 2)]
    board.loc['Charleston','Alanta'] = [('any',2)]
    board.loc['Alanta','Miami'] = [('blue',5)]
    board.loc['Miami','Alanta'] = [('blue',5)]
    board.loc['New Orleans', 'Alanta'] = [('yellow',4),('orange',4)]
    board.loc['Alanta','New Orleans'] = [('yellow',4),('orange',4)]
    board.loc['Little Rock','Dallas'] = [('any',2)]
    board.loc['Dallas','Little Rock'] = [('any',2)]
    board.loc['New Orleans','Miami'] = [('red',6)]
    board.loc['Miami','New Orleans'] = [('red',6)]
    board.loc['New Orleans', 'Houston'] = [('any',2)]
    board.loc['Houston','New Orleans'] = [('any',2)]
    board.loc['Houston','Dallas'] = [('any',1)]
    board.loc['Dallas','Houston'] = [('any',1)]
    board.loc['Dallas','El Palo'] = [('red',4)]
    board.loc['El Palo','Dallas'] = [('red',4)]
    board.loc['El Palo','Houston'] = [('green',6)]
    board.loc['Houston','El Palo'] = [('green',6)]


    print(board)

Creating_The_Board()